package engine

import (
	"context"
)

// LLMResponse represents the result generated by the language model
type LLMResponse struct {
	Text     string     `json:"text"`
	ToolCall *LLMToolCall `json:"toolCall,omitempty"`
}

type LLMToolCall struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Arguments string `json:"arguments"`
}

// LLMProvider defines the interface for text generation models
type LLMProvider interface {
	GetProviderID() string
	GenerateCompletion(ctx context.Context, systemPrompt string, userMessage string, tools []AgentTool) (*LLMResponse, error)
}

// OpenAILLM represents the OpenAI LLM implementation
type OpenAILLM struct {
	apiKey string
}

func NewOpenAILLM(apiKey string) *OpenAILLM {
	return &OpenAILLM{apiKey: apiKey}
}

func (o *OpenAILLM) GetProviderID() string {
	return "openai"
}

func (o *OpenAILLM) GenerateCompletion(ctx context.Context, systemPrompt string, userMessage string, tools []AgentTool) (*LLMResponse, error) {
	return &LLMResponse{
		Text: "Hello, this is an OpenAI LLM response.",
	}, nil
}

// AnthropicLLM represents the Anthropic LLM implementation
type AnthropicLLM struct {
	apiKey string
}

func NewAnthropicLLM(apiKey string) *AnthropicLLM {
	return &AnthropicLLM{apiKey: apiKey}
}

func (a *AnthropicLLM) GetProviderID() string {
	return "anthropic"
}

func (a *AnthropicLLM) GenerateCompletion(ctx context.Context, systemPrompt string, userMessage string, tools []AgentTool) (*LLMResponse, error) {
	return &LLMResponse{
		Text: "Hello, this is an Anthropic Claude response.",
	}, nil
}

// GroqLLM represents the Groq LLM implementation
type GroqLLM struct {
	apiKey string
}

func NewGroqLLM(apiKey string) *GroqLLM {
	return &GroqLLM{apiKey: apiKey}
}

func (g *GroqLLM) GetProviderID() string {
	return "groq"
}

func (g *GroqLLM) GenerateCompletion(ctx context.Context, systemPrompt string, userMessage string, tools []AgentTool) (*LLMResponse, error) {
	return &LLMResponse{
		Text: "Hello, this is an ultra low latency Groq response.",
	}, nil
}
