package engine

import (
	"context"
)

// STTTranscript represents a transcript segment generated by Speech-to-Text
type STTTranscript struct {
	Text       string  `json:"text"`
	Confidence float64 `json:"confidence"`
	IsFinal    bool    `json:"isFinal"`
}

// STTProvider defines the contract for real-time speech-to-text processing
type STTProvider interface {
	GetProviderID() string
	// StartStream opens a bidirectional connection or stream session to process streaming PCM audio chunks
	StartStream(ctx context.Context, sampleRate int, channels int) (chan<- []byte, <-chan STTTranscript, error)
}

// DeepgramSTT represents the Deepgram implementation
type DeepgramSTT struct {
	apiKey string
}

func NewDeepgramSTT(apiKey string) *DeepgramSTT {
	return &DeepgramSTT{apiKey: apiKey}
}

func (d *DeepgramSTT) GetProviderID() string {
	return "deepgram"
}

func (d *DeepgramSTT) StartStream(ctx context.Context, sampleRate int, channels int) (chan<- []byte, <-chan STTTranscript, error) {
	audioCh := make(chan []byte, 100)
	transcriptCh := make(chan STTTranscript, 50)

	// In Pipeline Mode, we stream raw audio in and receive decoded text chunks
	go func() {
		defer close(transcriptCh)
		for {
			select {
			case <-ctx.Done():
				return
			case _, ok := <-audioCh:
				if !ok {
					return
				}
				// Mock transcription output for pipeline testing
				transcriptCh <- STTTranscript{
					Text:       "hello world from deepgram",
					Confidence: 0.98,
					IsFinal:    true,
				}
			}
		}
	}()

	return audioCh, transcriptCh, nil
}

// AssemblyAISTT represents the AssemblyAI implementation
type AssemblyAISTT struct {
	apiKey string
}

func NewAssemblyAISTT(apiKey string) *AssemblyAISTT {
	return &AssemblyAISTT{apiKey: apiKey}
}

func (a *AssemblyAISTT) GetProviderID() string {
	return "assemblyai"
}

func (a *AssemblyAISTT) StartStream(ctx context.Context, sampleRate int, channels int) (chan<- []byte, <-chan STTTranscript, error) {
	audioCh := make(chan []byte, 100)
	transcriptCh := make(chan STTTranscript, 50)

	go func() {
		defer close(transcriptCh)
		for {
			select {
			case <-ctx.Done():
				return
			case _, ok := <-audioCh:
				if !ok {
					return
				}
				transcriptCh <- STTTranscript{
					Text:       "hello world from assemblyai",
					Confidence: 0.95,
					IsFinal:    true,
				}
			}
		}
	}()

	return audioCh, transcriptCh, nil
}
