// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/call/outbound": {
            "post": {
                "description": "Initiates an outbound call via Twilio and connects the voice channel to the WebSocket stream",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Telephony"
                ],
                "summary": "Trigger an outbound voice call",
                "parameters": [
                    {
                        "description": "Outbound Call Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/telephony.OutboundCallRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/telephony.OutboundCallResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/telephony.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/telephony.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "telephony.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid request body"
                }
            }
        },
        "telephony.OutboundCallRequest": {
            "type": "object",
            "required": [
                "agentPrompt",
                "targetNumber",
                "tenantId"
            ],
            "properties": {
                "agentPrompt": {
                    "type": "string",
                    "example": "You are a friendly assistant."
                },
                "targetNumber": {
                    "type": "string",
                    "example": "+15550199"
                },
                "tenantId": {
                    "type": "string",
                    "example": "tenant-123"
                }
            }
        },
        "telephony.OutboundCallResponse": {
            "type": "object",
            "properties": {
                "callSid": {
                    "type": "string",
                    "example": "CAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
                },
                "status": {
                    "type": "string",
                    "example": "queued"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Vocal Engine AI Agent Microservice API",
	Description:      "Microservice engine handling low latency bidirectionnal Twilio-to-LLM audio routing and asynchronous tool calling.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
