// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/agents": {
            "get": {
                "description": "Retrieves all voice agent profiles currently registered in the system",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agents"
                ],
                "summary": "List configured AI Agents",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/engine.Agent"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Configures an AI agent's voice, prompts, tools, STT/TTS engine, and failover fallbacks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agents"
                ],
                "summary": "Create an AI Agent profile",
                "parameters": [
                    {
                        "description": "Agent Profile Specifications",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/engine.Agent"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/engine.Agent"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/telephony.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/call/inbound": {
            "post": {
                "description": "Receives webhook requests from Twilio for incoming calls and connects them to a configured agent stream",
                "produces": [
                    "text/xml"
                ],
                "tags": [
                    "Telephony"
                ],
                "summary": "Handle Inbound Telephony Webhooks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Registered Agent ID",
                        "name": "agentId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Registered Tenant ID",
                        "name": "tenantId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "TwiML XML response",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/telephony.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/call/outbound": {
            "post": {
                "description": "Initiates an outbound call via Twilio and connects the voice channel to the WebSocket stream",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Telephony"
                ],
                "summary": "Trigger an outbound voice call",
                "parameters": [
                    {
                        "description": "Outbound Call Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/telephony.OutboundCallRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/telephony.OutboundCallResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/telephony.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/telephony.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "engine.Agent": {
            "type": "object",
            "properties": {
                "fallbackChain": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"groq\"",
                        " \"anthropic\"]"
                    ]
                },
                "firstMessage": {
                    "type": "string",
                    "example": "Hello! Thank you for calling Acme. How can I help you?"
                },
                "id": {
                    "type": "string",
                    "example": "agent-99"
                },
                "llmProviderId": {
                    "type": "string",
                    "example": "openai"
                },
                "maxDurationSec": {
                    "type": "integer",
                    "example": 600
                },
                "mode": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/engine.Mode"
                        }
                    ],
                    "example": "realtime"
                },
                "name": {
                    "type": "string",
                    "example": "Acme Receptionist"
                },
                "sttProviderId": {
                    "type": "string",
                    "example": "deepgram"
                },
                "systemPrompt": {
                    "type": "string",
                    "example": "You are a helpful office receptionist."
                },
                "tenantId": {
                    "type": "string",
                    "example": "tenant-123"
                },
                "tools": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/engine.AgentTool"
                    }
                },
                "ttsProviderId": {
                    "type": "string",
                    "example": "elevenlabs"
                },
                "vadSensitivity": {
                    "type": "number",
                    "example": 0.5
                },
                "voice": {
                    "type": "string",
                    "example": "alloy"
                }
            }
        },
        "engine.AgentTool": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Get details for a customer"
                },
                "name": {
                    "type": "string",
                    "example": "get_customer_info"
                },
                "parameters": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "engine.Mode": {
            "type": "string",
            "enum": [
                "realtime",
                "pipeline"
            ],
            "x-enum-comments": {
                "ModePipeline": "Orchestrated (STT -\u003e LLM -\u003e TTS)",
                "ModeRealtime": "Bidirectional WebSockets OpenAI/Groq"
            },
            "x-enum-descriptions": [
                "Bidirectional WebSockets OpenAI/Groq",
                "Orchestrated (STT -\u003e LLM -\u003e TTS)"
            ],
            "x-enum-varnames": [
                "ModeRealtime",
                "ModePipeline"
            ]
        },
        "telephony.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid request body"
                }
            }
        },
        "telephony.OutboundCallRequest": {
            "type": "object",
            "required": [
                "agentPrompt",
                "targetNumber",
                "tenantId"
            ],
            "properties": {
                "agentPrompt": {
                    "type": "string",
                    "example": "You are a friendly assistant."
                },
                "targetNumber": {
                    "type": "string",
                    "example": "+15550199"
                },
                "tenantId": {
                    "type": "string",
                    "example": "tenant-123"
                }
            }
        },
        "telephony.OutboundCallResponse": {
            "type": "object",
            "properties": {
                "callSid": {
                    "type": "string",
                    "example": "CAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
                },
                "status": {
                    "type": "string",
                    "example": "queued"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Vocal Engine AI Agent Microservice API",
	Description:      "Microservice engine handling low latency bidirectionnal Twilio-to-LLM audio routing and asynchronous tool calling.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
